# Site settings
title: Viettranx's Tek Blog
motto: Share more and learn more :)
email: viettrax@gmail.com
description: "Tek Blog - Những kiến thức lập trình C, Objective-C, iOS và Mac OSX."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://viettranx.github.io" # the base hostname & protocol for your site

facebookID: "viettranx"
# Build settings
markdown: kramdown
highlighter: pygments
timezone: Asia/Ho_Chi_Minh
excerpt_separator: <!--more-->

# Config disqus
disqus_shortname: viettx

# Config GA
GA_ID: "UA-64755268-1"
