# Site settings
title: Viettranx's Tek Blog
motto: Mình tạo page để lưu lại kiến thức cũng như chia sẻ để học được nhiều hơn :)
email: viettrax@gmail.com
description: "Tek Blog - Những kiến thức lập trình C, Objective-C, iOS và Mac OSX."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://viettranx.github.io" # the base hostname & protocol for your site

facebookID: "viettranx"
# Build settings
markdown: kramdown
highlighter: pygments
timezone: Asia/Ho_Chi_Minh

# Config disqus
disqus_shortname: viettx

# Config GA
GA_ID: "UA-64755268-1"
